Upgrade to rails 6
pulibrary/DSS pull request #244
Opened 2022-04-15 21:29 UTC by sandbergja

Depends on https://github.com/pulibrary/pul_assets/pull/76 being merged.

Also, Blacklight removed the saved search functionality in 7.0 (https://github.com/projectblacklight/blacklight/pull/1736), so we would need to re-implement if it is useful in the DSS app.

2022-04-20 15:13 UTC, sandbergja commented
Rebased to include the seed data from #249

2022-04-21 19:48 UTC, kevinreiss commented
I checked this out in staging and functionality generally looked good. Only two comments:

1. There seems to be some spacing issues with facet names. The wrapping is off. 
2. There also aren't any facet "breadcrumbs" appearing when you select a facet. 

2 may be expected behavior in this version of Blacklight, I don't know. 

<img width="1385" alt="Screen Shot 2022-04-21 at 2 47 52 PM" src="https://user-images.githubusercontent.com/278825/164541221-1b34012b-c21c-48b4-97c8-2c8ae670ef6e.png">
<img width="459" alt="Screen Shot 2022-04-21 at 2 47 10 PM" src="https://user-images.githubusercontent.com/278825/164541225-5c1661d6-2f7c-43a2-a914-83ad94434a0a.png">

2022-05-06 22:13 UTC, sandbergja commented
I reduced the spacing and got the constraints/breadcrumbs back.

The bookmarks feature was also missing, so I got that back too.

I noticed that the show page isn't displaying the sidebar with the email, sms, cite, and bookmark actions, though.  Still need to investigate that.

2022-05-09 19:14 UTC, carolyncole commented
@sandbergja was the link color change expected
New:
![Screen Shot 2022-05-09 at 3 13 25 PM](https://user-images.githubusercontent.com/1599081/167481091-e4cff538-a457-481d-830f-0a9ceee14a1a.png)
Old:
![Screen Shot 2022-05-09 at 3 13 31 PM](https://user-images.githubusercontent.com/1599081/167481146-c183b2e1-d039-4f90-a7bd-9ea7aeeaf6a0.png)

2022-05-09 19:21 UTC, carolyncole requested changes
The new color on the buttons is adding to the accessibility contrast issues.  We should likely go back to the old color scheme.
![Screen Shot 2022-05-09 at 3 19 06 PM](https://user-images.githubusercontent.com/1599081/167482115-5a0b0da8-d02e-4ada-b38e-30d1f7b09160.png)

2022-05-09 19:25 UTC, carolyncole commented
One other change I noted:  There are some links on the show page that are no longer clickable
Old:
![Screen Shot 2022-05-09 at 3 23 59 PM](https://user-images.githubusercontent.com/1599081/167482762-ea004b09-57e0-46c1-86e5-1e560835bce6.png)
New:
![Screen Shot 2022-05-09 at 3 24 09 PM](https://user-images.githubusercontent.com/1599081/167482825-e17979ec-3b18-42b2-93fe-c499809f7107.png)

2022-05-09 19:28 UTC, carolyncole commented
Sorry!  Another thing on the show page.  The very top header goes away:
Old:
![Screen Shot 2022-05-09 at 3 26 50 PM](https://user-images.githubusercontent.com/1599081/167483271-95a3e59f-e103-4d99-b1be-5c20a0208374.png)

New:
![Screen Shot 2022-05-09 at 3 27 04 PM](https://user-images.githubusercontent.com/1599081/167483156-b69edb81-2e6b-4dd8-bc4e-c07cce3f71af.png).

2022-05-09 19:28 UTC, carolyncole commented on .circleci/config.yml
> +      - browser-tools/install-chrome
🎉

2022-05-09 21:58 UTC, sandbergja commented
Thanks for catching all this, @carolyncole!  I've resolved everything except for the new green color for applied facets.  It's something that was added in the new Blacklight version.  Maybe we can discuss it a bit at tomorrow's meeting?

2022-05-09 22:13 UTC, carolyncole approved these changes
I'm not merging, since we want to have a discussion on the green.  I am approving though because the accessibility issue is gone! 🎉 
![Screen Shot 2022-05-09 at 6 11 59 PM](https://user-images.githubusercontent.com/1599081/167507182-9b00490e-27d9-4cb1-aa13-45adecad56d0.png)

2022-05-13 20:38 UTC, kevinreiss approved these changes

2022-05-13 20:38 UTC, merged